---
- name: "Install python 2 on Ubuntu 16.04 LTS"
  hosts: all
  become: true
  gather_facts: no
  pre_tasks:
    - raw: sudo apt-get update
    - raw: test -e /usr/bin/python || sudo apt-get -y install python-simplejson
    - setup: # aka gather facts
